version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      root-deps:
        patterns: ['*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
    groups:
      web-deps:
        patterns: ['*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: npm
    directory: /functions
    schedule:
      interval: weekly
      day: monday
    groups:
      functions-deps:
        patterns: ['*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
