coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 50%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false

flags:
  web:
    paths:
      - web/src/
    carryforward: true
  functions:
    paths:
      - functions/src/
    carryforward: true
